FROM debian:latest

# Instalar dependencias necesarias y agregar el repositorio Sury
RUN apt-get update && apt-get install -y \
    lsb-release \
    apt-transport-https \
    ca-certificates \
    wget && \
    wget -O /etc/apt/trusted.gpg.d/sury-keyring.gpg https://packages.sury.org/php/apt.gpg && \
    echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/sury.list && \
    apt-get update

# Instalar PHP 7.4, sus extensiones y Nginx
RUN apt-get install -y \
    php7.4-fpm \
    php7.4-mysql \
    php7.4-xml \
    php7.4-mbstring \
    php7.4-gd \
    php7.4-curl \
    php7.4-zip \
    php7.4-bz2 \
    php7.4-intl \
    nginx \
    && rm -rf /var/lib/apt/lists/*

# Configuración de PHP-FPM
COPY ./www.conf /etc/php/7.4/fpm/pool.d/www.conf

# Exponer el puerto usado por PHP-FPM
EXPOSE 9000

# Comando de inicio para PHP-FPM y Nginx
CMD php-fpm7.4 -D && nginx -g "daemon off;"

RUN chown -R www-data:www-data /var/www/html/

RUN chmod -R 770 /var/www/html/
