FROM nginx:latest

# Copiar el archivo de configuración de Nginx 
COPY nginxweb.conf /etc/nginx/conf.d/default.conf

# Exponer el puerto 80 para Nginx
EXPOSE 80

# Iniciar Nginx y PHP-FPM
CMD ["nginx", "-g", "daemon off;"]

ADD ./owncloud /var/www/html
WORKDIR /var/www/html

RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html
